[colors]
transparent_background_colors = true

[[colors.indexed_colors]]
color = "0x3ddbd9"
index = 16

[[colors.indexed_colors]]
color = "0xff7eb6"
index = 17

[colors.bright]
black = "0x484848"
blue = "0x8cb6ff"
cyan = "0x52bdff"
green = "0x46c880"
magenta = "0xc8a5ff"
red = "0xf16da6"
white = "0xe4e4e5"
yellow = "0x2dc7c4"

[colors.normal]
black = "0x282828"
blue = "0x78a9ff"
cyan = "0x33b1ff"
green = "0x25be6a"
magenta = "0xbe95ff"
red = "0xee5396"
white = "0xdfdfe0"
yellow = "0x08bdba"

[colors.primary]
background = "0x161616"
foreground = "0xf2f4f8"

[cursor.style]
shape = "Block"

[font]
size = 17.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Medium"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"

[mouse]
hide_when_typing = true

[shell]
args = ["--login", "--init-command", "~/.config/scripts/tmux-sessionizer"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "none"
dynamic_title = false
opacity = 0.92

[window.padding]
x = 5
y = 5
